/* English Adventure 主程式：畫面、卡牌、遊戲與進度。 */
const AdventureApp=(()=>{
  let state=AdventureStorage.load(),topicId=state.lastTopic||"home",mode="cards",currentItem=null,collectionFilter="all";
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const topic=()=>TOPICS.find(t=>t.id===topicId),items=()=>LEARNING_DATA.filter(x=>x.category===topicId);
  const cardRecord=id=>state.cards[id]||{collected:false,favorite:false,correct:0,wrong:0,mastery:0};
  const names=["仁偉","怡恩","雨葳","可芸","星岑","若綺","宸熙","宸楷","苡瑄","辰淮","測試1","測試2"];
  const learnerName=()=>names[Number(AdventureStorage.learner())]||"小小探險家";
  const completion=id=>Math.min(100,Math.round(((state.topicWins[id]||0)/5)*100));
  function persist(){AdventureStorage.save(state);renderHeader()}
  function show(view){$$(".view").forEach(v=>v.classList.toggle("active",v.id===view));scrollTo({top:0,behavior:"smooth"});if(view==="homeView")renderHome();if(view==="collectionView")renderCollection();if(view==="badgesView")renderBadges();if(view==="recordsView")renderRecords()}
  function toast(text){const t=$("#toast");t.textContent=text;t.classList.add("show");clearTimeout(t.timer);t.timer=setTimeout(()=>t.classList.remove("show"),2200)}
  window.adventureToast=toast;
  function sound(kind="click"){if(!state.sound)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const c=new AC(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=kind==="win"?660:kind==="hint"?300:480;g.gain.setValueAtTime(.05,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.16);o.start();o.stop(c.currentTime+.17)}
  function renderHeader(){$("#playerName").textContent=learnerName();$("#levelLabel").textContent=`Lv.${state.level}`;$("#starLabel").textContent=`⭐ ${state.stars}`;$("#soundToggle").textContent=state.sound?"🔊":"🔇";$("#soundToggle").setAttribute("aria-label",state.sound?"關閉音效":"開啟音效");$("#xpBar").style.width=`${state.xp%100}%`;$("#dailyProgress").textContent=`${Math.min(state.daily,3)} / 3`;$("#dailyBar").style.width=`${Math.min(100,state.daily/3*100)}%`;const chest=state.correct%5;$("#chestBar").style.width=`${chest/5*100}%`;$("#chestText").textContent=chest?`再答對 ${5-chest} 題開啟`:`已開啟 ${state.chests||0} 個寶箱`;$("#streakLabel").textContent=`🔥 連續學習 ${state.streak} 天`}
  function updateLearningDay(){const today=new Date().toISOString().slice(0,10);if(state.lastActive===today)return;const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);state.streak=state.lastActive===yesterday?(state.streak||0)+1:1;state.daily=0;state.lastActive=today;persist()}
  function starAnimation(){const layer=$("#starLayer");for(let i=0;i<5;i++){const star=document.createElement("span");star.className="flying-star";star.textContent="⭐";star.style.setProperty("--star-x",`${(i-2)*52}px`);star.style.animationDelay=`${i*55}ms`;layer.append(star);setTimeout(()=>star.remove(),1200)}}
  function showCelebration(){const t=topic();$("#celebrationBadge").textContent="🏅";$("#celebrationTitle").textContent=`${t.name}關卡完成！`;$("#celebrationText").textContent=`獲得「${t.badge}」主題徽章！小狐狸為你歡呼！`;$("#celebration").classList.remove("hidden")}
  function renderHome(){
    renderHeader();$("#mapGrid").innerHTML=TOPICS.map((t,i)=>{const locked=i>=state.unlocked,p=completion(t.id);return `<button class="map-node ${locked?"locked":""}" data-topic="${t.id}" ${locked?"disabled":""} style="--topic:${t.color}"><span class="map-icon">${t.icon}</span><strong>${t.name} <small>${t.english}</small></strong><small>${p>=100?"🏅 已完成":"完成度 "+p+"%"}</small><span class="node-progress"><span style="width:${p}%"></span></span></button>`}).join("");
    const collected=Object.values(state.cards).filter(x=>x.collected).length,badges=TOPICS.filter(t=>completion(t.id)>=100).length;$("#collectionSummary").textContent=`已收藏 ${collected} / 60`;$("#badgeSummary").textContent=`獲得 ${badges} / 6`;$$("[data-topic]").forEach(b=>b.onclick=()=>openTopic(b.dataset.topic))
  }
  function openTopic(id){topicId=id;state.lastTopic=id;persist();renderTopic();show("topicView")}
  function renderTopic(){const t=topic();$("#topicEnglish").textContent=t.english;$("#topicTitle").textContent=`${t.icon} ${t.name}`;$("#topicProgress").textContent=`完成度 ${completion(t.id)}%`;$$(".mode-picker button").forEach(b=>b.classList.toggle("active",b.dataset.mode===mode));renderMode()}
  function renderMode(){const c=$("#topicContent");if(mode==="cards"){c.innerHTML=`<div class="card-grid">${items().map(cardMarkup).join("")}</div>`;bindCards();return}currentItem=AdventureGames.shuffle(items())[0];if(mode==="picture")c.innerHTML=AdventureGames.picture(currentItem,items());if(mode==="listen")c.innerHTML=AdventureGames.listen(currentItem,items());if(mode==="order")c.innerHTML=AdventureGames.order(currentItem);bindGame();if(mode==="listen")setTimeout(()=>AdventureSpeech.speak(currentItem.phrase,.82,$("[data-speak]")),250)}
  function cardMarkup(item){const r=cardRecord(item.id),t=TOPICS.find(x=>x.id===item.category),stars="⭐".repeat(Math.max(1,Math.ceil(r.mastery/34)));return `<article class="learn-card" data-card="${item.id}" style="--topic:${t.color}"><div class="card-inner"><section class="card-face front"><div class="mastery"><span>${t.icon} ${t.name}</span><span class="stars-text">${stars}</span></div><div class="card-picture" role="img" aria-label="${item.translation}">${item.image}</div><h3 data-text>${item.phrase}</h3><div class="card-actions"><button data-say-normal="${item.id}" aria-label="正常速度發音">🔊 正常</button><button data-say-slow="${item.id}" aria-label="慢速發音">🐢 慢速</button><button class="favorite ${r.favorite?"active":""}" data-favorite="${item.id}" aria-label="收藏卡牌">${r.favorite?"♥":"♡"}</button><button data-flip="${item.id}">翻牌 ↻</button></div></section><section class="card-face back"><h3 data-text>${item.phrase}</h3><strong>${item.translation}</strong><p><b>使用時機：</b>${item.usage}</p><p data-example><b>例句：</b>${item.example}<br><small>${item.exampleTranslation}</small></p><div class="dialogue"><b>情境對話</b>${item.dialogue.map(x=>`<p>${x.speaker}: ${x.text}</p>`).join("")}</div><div class="mastery"><span>熟練度 ${r.mastery}%</span><span>✓ ${r.correct}　↻ ${r.wrong}</span></div><div class="card-actions"><button data-example-speak="${item.id}">🔊 例句</button><button data-dialogue="${item.id}">💬 對話</button><button data-challenge="${item.id}">▶ 挑戰</button><button data-flip="${item.id}">返回 ↻</button></div></section></div></article>`}
  const find=id=>LEARNING_DATA.find(x=>x.id===id);
  function ensureCard(id){state.cards[id]=cardRecord(id);return state.cards[id]}
  function bindCards(){
    $$("[data-flip]").forEach(b=>b.onclick=()=>b.closest(".learn-card").classList.toggle("flipped"));
    $$("[data-say-normal]").forEach(b=>b.onclick=()=>{const x=find(b.dataset.sayNormal);ensureCard(x.id).collected=true;persist();AdventureSpeech.speak(x.phrase,.85,b.closest(".card-face").querySelector("[data-text]"))});
    $$("[data-say-slow]").forEach(b=>b.onclick=()=>AdventureSpeech.speak(find(b.dataset.saySlow).phrase,.55,b.closest(".card-face").querySelector("[data-text]")));
    $$("[data-example-speak]").forEach(b=>b.onclick=()=>AdventureSpeech.speak(find(b.dataset.exampleSpeak).example,.82,b.closest(".card-face").querySelector("[data-example]")));
    $$("[data-dialogue]").forEach(b=>b.onclick=()=>AdventureSpeech.dialogue(find(b.dataset.dialogue).dialogue,b.closest(".card-face").querySelector(".dialogue")));
    $$("[data-favorite]").forEach(b=>b.onclick=()=>{const r=ensureCard(b.dataset.favorite);r.favorite=!r.favorite;r.collected=true;persist();if($("#collectionView").classList.contains("active"))renderCollection(collectionFilter);else renderMode()});
    $$("[data-challenge]").forEach(b=>b.onclick=()=>{currentItem=find(b.dataset.challenge);mode="picture";renderTopic()})
  }
  function reward(item){const r=ensureCard(item.id);r.collected=true;r.correct++;r.mastery=Math.min(100,r.mastery+15);const before=state.correct;state.correct++;state.stars+=2;state.xp+=20;state.daily++;state.sessions++;if(Math.floor(state.correct/5)>Math.floor(before/5)){state.chests=(state.chests||0)+1;toast("🧰 寶箱開啟！獲得額外 ⭐");state.stars++;sound("win")}const today=new Date().toISOString().slice(0,10);state.days[today]=(state.days[today]||0)+1;const previousWins=state.topicWins[topicId]||0;state.topicWins[topicId]=previousWins+1;if(state.xp>=state.level*100){state.level++;sound("win");toast(`🎉 升到第 ${state.level} 級！`)}const i=TOPICS.findIndex(t=>t.id===topicId);if((state.topicWins[topicId]||0)>=3&&state.unlocked<i+2){state.unlocked=Math.min(TOPICS.length,i+2);toast("🔓 新地圖解鎖！")}starAnimation();$("#buddyMessage").textContent="答對了！你是很棒的英文探險家！";$("#buddy").classList.add("cheer");setTimeout(()=>$("#buddy").classList.remove("cheer"),700);persist();if(previousWins<5&&state.topicWins[topicId]>=5)setTimeout(showCelebration,750)}
  function wrong(item){const r=ensureCard(item.id);r.wrong++;state.wrong++;state.mistakes[item.id]=(state.mistakes[item.id]||0)+1;$("#buddyMessage").textContent="沒關係！再聽一次提示，你一定做得到！";persist()}
  function bindGame(){
    $$("[data-speak]").forEach(b=>b.onclick=()=>AdventureSpeech.speak(find(b.dataset.speak).phrase,.82,b));$$("[data-answer]").forEach(b=>b.onclick=()=>answer(b,b.dataset.answer===currentItem.id));
    $$(".word-chip").forEach(b=>{let startX=0,startY=0,dragging=false,ghost=null,dropTarget=null,suppressClick=false;
      b.onclick=()=>{if(suppressClick){suppressClick=false;return}const target=b.parentElement.id==="wordBank"?$("#answerBank"):$("#wordBank");target.append(b);AdventureSpeech.speak(b.dataset.word,.8)};
      b.ondragstart=e=>{e.dataTransfer.setData("text/plain",b.dataset.word);e.dataTransfer.effectAllowed="move"};
      b.onpointerdown=e=>{if(e.pointerType==="mouse")return;startX=e.clientX;startY=e.clientY;dragging=false;try{b.setPointerCapture?.(e.pointerId)}catch{}};
      b.onpointermove=e=>{if(e.pointerType==="mouse")return;if(!dragging&&Math.hypot(e.clientX-startX,e.clientY-startY)>10){dragging=true;suppressClick=true;b.classList.add("touch-dragging");ghost=document.createElement("div");ghost.className="touch-drag-ghost";ghost.textContent=b.dataset.word;document.body.append(ghost)}if(!dragging)return;e.preventDefault();ghost.style.left=`${e.clientX}px`;ghost.style.top=`${e.clientY}px`;dropTarget=document.elementFromPoint(e.clientX,e.clientY)?.closest(".drop-zone");$$(".drop-zone").forEach(zone=>zone.classList.toggle("drag-over",zone===dropTarget))};
      b.onpointerup=b.onpointercancel=e=>{if(e.pointerType==="mouse"||!dragging)return;if(dropTarget)dropTarget.append(b);ghost?.remove();b.classList.remove("touch-dragging");$$(".drop-zone").forEach(zone=>zone.classList.remove("drag-over"));dragging=false;dropTarget=null;setTimeout(()=>suppressClick=false,350)}
    });
    $$(".drop-zone").forEach(zone=>{zone.ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect="move"};zone.ondrop=e=>{e.preventDefault();const word=e.dataTransfer.getData("text/plain"),chip=$$(".word-chip").find(x=>x.dataset.word===word);if(chip)zone.append(chip)}});
    if($("#checkOrder"))$("#checkOrder").onclick=checkOrder
  }
  function answer(b,ok){const f=$("#gameFeedback");if(ok){b.classList.add("correct");f.textContent="Excellent! 太棒了！獲得 ⭐⭐";reward(currentItem);sound("win");AdventureSpeech.speak(currentItem.phrase,.82,b);setTimeout(renderMode,1500)}else{b.classList.add("hint");f.textContent="Almost there! 再聽一次提示，不扣星星。";wrong(currentItem);sound("hint");AdventureSpeech.speak(currentItem.phrase,.65);setTimeout(()=>b.classList.remove("hint"),900)}}
  function checkOrder(){const answer=[...$("#answerBank").children].map(x=>x.dataset.word).join(" "),target=currentItem.phrase.replace(/[.!?]/g,"");if(answer===target){$("#gameFeedback").textContent="Great job! 句子排對了！獲得 ⭐⭐";reward(currentItem);sound("win");AdventureSpeech.speak(currentItem.phrase,.82,$("#answerBank"));setTimeout(renderMode,1700)}else{$("#gameFeedback").textContent="Almost there! 看看開頭單字和順序，再試一次。";wrong(currentItem);sound("hint")}}
  function renderCollection(filter="all"){collectionFilter=filter;const collected=LEARNING_DATA.filter(x=>cardRecord(x.id).collected).length;$("#collectionCount").textContent=`${collected} / 60`;$("#collectionFilters").innerHTML=[{id:"all",name:"全部"},...TOPICS].map(t=>`<button class="${filter===t.id?"active":""}" data-filter="${t.id}">${t.icon||"✨"} ${t.name}</button>`).join("");$("#collectionGrid").innerHTML=LEARNING_DATA.filter(x=>filter==="all"||x.category===filter).map(x=>cardRecord(x.id).collected?cardMarkup(x):`<article class="card-face" style="position:relative;min-height:260px;filter:grayscale(1);opacity:.55"><div class="card-picture">❔</div><h3>尚未解鎖</h3><p>到主題地圖學習這張卡牌。</p></article>`).join("");$$("[data-filter]").forEach(b=>b.onclick=()=>renderCollection(b.dataset.filter));bindCards()}
  function renderBadges(){$("#badgeGrid").innerHTML=TOPICS.map(t=>{const won=completion(t.id)>=100;return `<article class="achievement ${won?"":"locked"}"><span>${won?"🏅":"🔒"}</span><h3>${t.badge}</h3><p>${won?`完成 ${t.name} 綜合挑戰！`:`${t.name} 完成度達 100% 後取得`}</p></article>`}).join("")}
  function renderRecords(){const learned=Object.values(state.cards).filter(x=>x.collected).length,total=state.correct+state.wrong,accuracy=total?Math.round(state.correct/total*100):0;$("#recordStats").innerHTML=[["已學會句子",learned],["練習次數",state.sessions],["正確率",`${accuracy}%`],["發音練習",state.pronunciation],["連續學習",`${state.streak} 天`],["累積時間",`${state.minutes} 分鐘`]].map(x=>`<div class="record-stat"><strong>${x[1]}</strong><small>${x[0]}</small></div>`).join("");const days=[...Array(7)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));return d}),values=days.map(d=>state.days[d.toISOString().slice(0,10)]||0),max=Math.max(1,...values);$("#weekChart").innerHTML=days.map((d,i)=>`<div class="day-bar"><span>${values[i]}</span><i style="height:${values[i]/max*110}px"></i><small>${["日","一","二","三","四","五","六"][d.getDay()]}</small></div>`).join("");$("#topicRecords").innerHTML=TOPICS.map(t=>`<div class="topic-record"><strong>${t.icon} ${t.name}</strong><div class="progress"><span style="width:${completion(t.id)}%"></span></div><span>${completion(t.id)}%</span></div>`).join("");const m=Object.entries(state.mistakes).sort((a,b)=>b[1]-a[1]).slice(0,5);$("#mistakeRecords").innerHTML=m.length?m.map(([id,n])=>`<p><strong>${find(id)?.phrase||id}</strong> — 再練習 ${n} 次</p>`).join(""):"<p>目前沒有常錯句子，繼續保持！</p>"}
  function init(){updateLearningDay();renderHome();$$("[data-open]").forEach(b=>b.onclick=()=>show(b.dataset.open));$(".mode-picker").onclick=e=>{const b=e.target.closest("[data-mode]");if(!b)return;mode=b.dataset.mode;renderTopic()};$("#continueButton").onclick=()=>openTopic(state.lastTopic||"home");$("#soundToggle").onclick=()=>{state.sound=!state.sound;persist();toast(state.sound?"音效已開啟":"音效已關閉")};$("#celebrationDone").onclick=()=>$("#celebration").classList.add("hidden");$("#clearProgress").onclick=()=>{if(confirm("確定要清除這位學習者的英文遊戲紀錄嗎？清除後無法復原。")){AdventureStorage.reset();state=AdventureStorage.load();updateLearningDay();renderRecords();renderHeader();toast("學習紀錄已清除")}};if(!state.tutorial){const steps=[["歡迎來到英語生活大冒險！","先從家庭地圖開始，點卡牌就能聽英文。"],["收集卡牌與星星","翻開卡牌看例句，完成挑戰會增加熟練度與寶箱進度。"],["放心開口、多試幾次","答錯不扣星星，小狐狸會給提示。準備好就出發！"]];let step=0;$("#tutorial").classList.remove("hidden");$("#tutorialDone").onclick=()=>{step++;if(step>=steps.length){state.tutorial=true;persist();$("#tutorial").classList.add("hidden");return}$("#tutorialStep").textContent=`新手引導 ${step+1} / 3`;$("#tutorialTitle").textContent=steps[step][0];$("#tutorialText").textContent=steps[step][1];$$(".tutorial-dots i").forEach((dot,i)=>dot.classList.toggle("active",i===step));$("#tutorialDone").textContent=step===2?"開始冒險！":"下一步"}}const preview=new URLSearchParams(location.search).get("preview");if(preview){$("#tutorial").classList.add("hidden");openTopic("home");if(preview==="back")requestAnimationFrame(()=>$(".learn-card [data-flip]")?.click())}setInterval(()=>{state.minutes++;persist()},60000)}
  function testApi(){return{show,openTopic,renderTopic,setMode:value=>{mode=value;renderTopic()},getCurrent:()=>currentItem,getState:()=>JSON.parse(JSON.stringify(state)),renderMode}}
  if(new URLSearchParams(location.search).has("test"))window.__adventureTest=testApi();
  return{init}
})();
document.addEventListener("DOMContentLoaded",AdventureApp.init);
